version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run: yarn install --frozen-lockfile --no-progress
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  prepublish:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: yarn prepack

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - prepublish:
          requires:
            - install
            - lint
      - publish:
          requires:
            - install
            - lint
            - prepublish
